homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ele
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml
      
# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret login_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# lights
light:
  platform: hue
  host: !secret hue_host
  allow_unreachable: true

# Text to speech
tts:
  platform: google

media_player:
  - platform: plex
    name: Plex
  - platform: kodi
    name: Kodi
    host: !secret kodi_host
    port: !secret kodi_port
    turn_off_action: quit
  - platform: cast
    name: ShieldTV
    host: !secret shield_tv
  - platform: cast
    name: Ambilight TV
    host: !secret ambilight_tv
  - platform: universal
    name: Cast Remote
    children:
      - media_player.kodi
      - media_player.shieldtv       # this is the plex media player
      - media_player.ambilight_tv
      - media_player.shield

remote:
  - platform: harmony
    name: Harmony TV
    host: !secret harmony_host
    port: !secret harmony_port
    activity: Streaming
    
device_tracker:
  - platform: nmap_tracker
    home_interval: 15
    hosts:
    - !secret mona_ip
  - platform: owntracks
    max_gps_accuracy: 200
  
zone:
  name: Home
  latitude: !secret lat
  longitude: !secret lon
  radius: 50
  icon: mdi:home-map-marker

zone 2:
  name: Work Stephan
  latitude: !secret zone_2_lat
  longitude: !secret zone_2_lon
  radius: 100
  icon: mdi:home-map-marker

zone 3:
  name: Work Mona
  latitude: !secret zone_3_lat
  longitude: !secret zone_3_lon
  radius: 100
  icon: mdi:home-map-marker

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password

input_slider:
  harmonyvolume:
    icon: mdi:volume-high
    name: Volume
    initial: 12
    min: 1
    max: 30
    step: 1

panel_iframe:
  sabnzbd:
    title: 'SABnzbd'
    icon: mdi:server
    url: !secret sabnzbd_url
  sickbeard:
    title: 'SickBeard'
    icon: mdi:server
    url: !secret sickbeard_url


group: !include groups.yaml
input_select: !include input_select.yaml
script: !include scripts.yaml
automation: !include automation.yaml
sensor: !include sensors.yaml


