- platform: template
  sensors:
    harmony_hub:
      value_template: '{{ states.remote.harmony_tv.attributes.current_activity }}'
      friendly_name: 'Harmony Hub'

- platform: systemmonitor
  resources:
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot
    
- platform: yr
  monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature

- platform: google_travel_time
  name: Mona zur Arbeit
  api_key: !secret google_api_key
  origin: zone.home
  destination: zone.work_mona
  options:
    mode: driving

- platform: google_travel_time
  name: Mona nach Hause
  api_key: !secret google_api_key
  origin: zone.work_mona
  destination: zone.home
  options:
    mode: driving

- platform: google_travel_time
  name: Stephan zur Arbeit
  api_key: !secret google_api_key
  origin: zone.home
  destination: zone.work_stephan
  options:
    mode: transit

- platform: google_travel_time
  name: Stephan nach Hause
  api_key: !secret google_api_key
  origin: zone.work_stephan
  destination: zone.home
  options:
    mode: transit

- platform: mqtt
  state_topic: "owntracks/phone/phone"
  name: "Stephans Phone Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'


